### PR TITLE
JWSTSIAF 164 on OSS 8.1

### PR DESCRIPTION
**Pull request by shanosborne**
This PR replaces #135 and is for JWSTSIAF-164
"We are delivering new apertures for this ticket. We are also adding placeholder distortion files for the new full-frame master apertures for coronographic modes. These distortion files will eventually account for the changes in distortion solution due to the introduction of the wedge into the optical path"

It was determined that the next PRD release would be a DEVSOC release based on the previous OSS 8.1 delivery, which is PRDOPSSOC-028. As pysiaf's master and siaf-updates branch are currently up to date with PRDOPSSOC-027 which is for OSS 8.2, the old branch/PR (#135) built the new JWSTSIAF-164 change on top of the OSS 8.2 data rather than the OSS 8.1 data. For this reason, we have closed the old PR and this new PR has been opened to add the same changes on top of the OSS 8.1 data.

Tagging @mgennaro who was the author of this change and the original PR

### CODE REVIEW

**Comment by shanosborne** [comment]
Detailed description from @mgennaro on the previous PR:

> The above commit e6c7df7 solves the issues we previously had when we introduced the new master apertures for dealing with distortions in NIRCam coronography.
> 
> Changes:
> -  introduce new master apertures (4 in total, 2 wedges x 2 channels). These are added in the siaf_detector_layout file as well as in the nircam_siaf_alignment file
> -  account for the V2,V3 shifts introduce by the wedges directly in the nircam_siaf_alignment. The previous design used a nircam_siaf_wedge_offset file and an ad-hoc dependency to achieve the same total offset. Currently the alignment file contains V2,V3 ref positions equal to the corresponding imaging ones, plus the offsets that can be read out of the wedge_offset files. These can in principle be modified in the future
> - introduce 4 new distortion files, one per each new master aperture. At this stage these are placeholder files copied from the previous imaging distortion files. they will be replaced with proper solution for the distortion for the coronographic field of view (an optics)
> - change the dependency type of ALL the coronographic apertures in module A in the nircam_siaf_aperture_definitions file. The dependency is no longer wedge, but a simple default dependency. The parent apertures for these apertures have been switched from e.g. NRCA2_FULL to NRCA2_FULL_WEDGE_RND and so on. This by-passes the part of the generate_nircam code that was adding the wedge offset to the V2,V3 ref positions of the coronographic apertures.
> 
> I have verified in several way that this new design works.
> By design the V2,V3 offset I am using is identical to that of the old design, in the wedge file. Also, the distortion coefficients are identical to those used before (cloned from the imaging distortion files). Thus after running generate_nircam, the SIAF.xml file has identical entries as those produced by the old code design, and this is expected. To verify that the code was reading the right inputs, I tweaked the input files in several test runs and verified that the changes propagated downstream into the SIAF.xml file. In particular:
> 
> - I tested that by artificially changing the V2,V3 positions in the alignment file, I was obtaining a correspondingly shifted V2,V3 position in the SIAF.xml file
> - I tested that by changing the distortion coefficients in the newly created distortion files for coronography, those coefficients end up correctly into the SIAF.xml file
> 
> As of now I believe the code changes are complete and everything finally works as expected. The next step will be to incorporate newer distortion coefficients to replace the placeholder ones, and possibly new global offset in the alignment file

**Comment by shanosborne** [comment]
I reviewed the changes in this PR and believe that these new parent apertures will work as expected. I also compared the changes to the files from the old PR vs this new one and believe I have moved all the changes over successfully (however, I would appreciate someone double checking this, as this PR was much more complicated to move). I do have 2 questions:

1. There are some apertures in the nircam_siaf_aperture_definition.txt file that still have a wedge dependency type - is that what the NIRCam team wants? (This was also true in the previous PR as is not from transferring the data to this new PR)
2. Some of the coronagraph apertures with new parents have differences in their Idl2Sci coefficients when comparing the PRDOPSSOC-028 data (which this PR was build on), and with these changes included. Is that an expected result of this PR? I was expecting no change in the SIAF XML files for the newly changed child apertures (the only change would be the added apertures). I've attached the 028 nircam siaf xml file to this comment (it will be included in pysiaf in the future)

[NIRCam_SIAF.xml.zip](https://github.com/spacetelescope/pysiaf/files/4493747/NIRCam_SIAF.xml.zip)

**Comment by shanosborne** [comment]
Quick Update: I've done some more checking and confirmed that:
1. All the new coronagraphic child apertures in nircam_siaf_aperture_definition.txt match the ones in the original PR (the values may have changes due to changes made in PRDOPSSOC-027, but the aperture name-parent aperture  pairs match
2. I compared the SIAF_NIRCam.xml files pre- and post- changes from the previous PR to see if that PR also showed changes to the Idl2Sci coefficients for the new coronagraphic child apertures, and it did show those changes. 
So I am convinced that this PR matches the previous one. However, my 2 questions above still apply

**Comment by shanosborne** [comment]
@mgennaro and I had a conversation about my two questions, here are our comments:

1. There have not been measurements made for the NRCB module, so we don't have the information to do the same switch to coronagraphic parent apertures like we did for NRCA. However this is fine because 1) we don't plan to use NRCB for commissioning and 2) we never took out the code and wedge offset file that deals with the wedge dependency type. So the NRCB apertures can still have a dependency type of "wedge" without breaking anything. We'll only need to come back to this if we determine that we need to use NRCB for commissioning.

2. All the differences in the coefficients are for the inverse transformation Idl2Sci (which requires extra computations compared to the Sci2Idl coefficients) and they all have a difference of <1e-06 which is why they don't appear in the diff analysis file. After preforming other checks (like confirming that the ~40arcsec offset in the siaf alignment file is present and that the new master apertures have the same coefficients as their imaging counterparts (e.g. NRCA2_FULL_WEDGE_RND vs NRCA2_FULL) in the siaf XML file) we feel confident that the data and code are being applied correctly, and these Idl2Sci discrepancies are just due to rounding/computer error

I will now upload the XML, excel, and analysis files to JIRA and wait for approval from the nircam team

**Comment by mgennaro** [comment]
Just a note for posterity, re: the above comment by shannon. I agree with everything and I wanted to clarify one detail:

> we don't plan to use NRCB for commissioning

In fact we don't plan to use NRCB for coronographic science.
However we will do some commissioning observations  to make sure we have data needed in case we should make an unforseen module A -> module B switch for coronography, but given that we don't plan to use module B in science operations, we do not need to develop NOW the full SIAF capacity as we are doing for module A (and hopefully we never will have to)

**Comment by shanosborne** [comment]
These changes were approved in a comment on the JWSTSIAF JIRA ticket and can now be merged

**Pull request merged**
