### PR TITLE
Roman dev - WIP

### PR DESCRIPTION
**Pull request by Witchblade101**
My quick-and-dirty attempt at adding the Roman SIAF to PySIAF from February. This definitely still needs some cleaning up, the tests added, and documentation, but I wanted to make sure Mees and Tyler have a chance to look at it.

### CODE REVIEW

**Comment by mfixstsci** [comment]
Hey @Witchblade101 thank you for submitting this! I can review it and let you know what I think!

**Review by mfixstsci — APPROVED** [review]
LGTM. I say we revisit this once the code for Roman matures a little but, but being able to generate the apertures is a great first step. Thanks @Witchblade101!

**Review by tddesjardins — APPROVED** [review]

**Comment by mfixstsci** [comment]
@Witchblade101 is this PR still a WIP? Besides displaying the apertures, have there been any more coding updates or changes @tddesjardins?

**Comment by tddesjardins** [comment]
@mfixstsci no further updates here. All the existing tools for transformations in pysiaf work for us, and we don't currently plan to include the SIAF generation code in this repo (at least, not yet?).

**Comment by bmorris3** [comment]
Hi folks! In jdaviz we now support instrument footprint overlays on images in Imviz (https://github.com/spacetelescope/jdaviz/pull/2341) via `pysiaf`. For example, here's the NIRCam FOV overlaid on a Roman exposure:

NIRCam on Roman exposure

Is there a timeline for merge for the Roman features in this PR? Thanks!

**Pull request merged**
