### PR TITLE
Updated with Dec 2023 Roman SIAF 

### PR DESCRIPTION
**Pull request by Witchblade101**
Updated with XML file from #329

### CODE REVIEW

**Review by mfixstsci — APPROVED** [review]
Looks good from a code stand point, did you test it yet to make sure you get the plot at the end @Witchblade101?

**Comment by Witchblade101** [comment]
> Looks good from a code stand point, did you test it yet to make sure you get the plot at the end @Witchblade101?

No, but I'll do that now.

**Comment by Witchblade101** [comment]
I think it looks good:

`import pysiaf
import numpy as np
import matplotlib.pyplot as plt
instrument = 'Roman'
siaf = pysiaf.Siaf(instrument)  

for aperture_name, aperture in siaf.apertures.items():
    aperture.plot()
plt.show()`

image

**Comment by mfixstsci** [comment]
Cool @Witchblade101 I am good with this

**Pull request merged**
