### PR TITLE
Replace placeholder values for the 4 NIRCam coronographic apertures with values from CODE-V model

### PR DESCRIPTION
**Pull request by mgennaro**
This PR follows the request of https://jira.stsci.edu/browse/JWSTSIAF-174 by the NIRCam team to deliver new values for the 4 coronographic master apertures, based on CODE V simulations of the NIRCam instrument with the coronograph in place in the beam.

The work will consist in:

- Addition of a new `nircam_cold_fit_coron.txt` file in `pysiaf/source_data/NIRCam/`, containing optical model info relevant to the coronographic apertures. This file is modeled after the `nircam_cold_fit.txt` file already available. The values in `nircam_cold_fit_coron.txt` are based on new simulations of the NIRCam optics w/ the coronograph in the beam

-  Modifications to the design of the `pysiaf/generate/generate_reference_files.py` script. These modifications are necessary to allow mapping and using the data for the new coronographic apertures that are in the new `nircam_cold_fit_coron.txt` file. 
Running the new version of the `pysiaf/generate/generate_reference_files.py` script will produce:
    1.  a new version of the `pysiaf/source_data/NIRCam/nircam_siaf_alignment.txt` file, containing the original info for the 10 imaging/WFSS master apertures and the new info for the 4 coronographic apertures, as derived from the `nircam_cold_fit_coron.txt` file
    2. updated values for the 4 coronographic distortion files, `nircam_siaf_distortion_nrca2_full_wedge_rnd.txt`, `nircam_siaf_distortion_nrca5_full_wedge_bar.txt`, 
`nircam_siaf_distortion_nrca4_full_wedge_bar.txt`, `nircam_siaf_distortion_nrca5_full_wedge_rnd.txt`

- Delivery of the above 4 distortion files and of the new `nircam_siaf_alignment.txt` file

### CODE REVIEW

**Comment by mgennaro** [comment]
FYI:
@ColinRCox @tonysohn @Johannes-Sahlmann @JAStansberry

**Comment by ColinRCox** [comment]
It looks as if you have everything under control.


On Jun 22, 2020, at 5:37 PM, Mario Gennaro <notifications@github.com<mailto:notifications@github.com>> wrote:



FYI:
@ColinRCox<https://github.com/ColinRCox> @tonysohn<https://github.com/tonysohn> @Johannes-Sahlmann<https://github.com/Johannes-Sahlmann> @JAStansberry<https://github.com/JAStansberry>

**Comment by mgennaro** [comment]
A small amendment to my proposed design above. In doing the work I realized it was easy enough to modify the existing code and have a single solution that is both backward compatible for the pre-exisiting 10 NIRCam imaging master apertures AND allows including the new 4 coronographic ones.
I didn't have to create a bifurcation in the code to deal with NIRCam imaging and coronographic master apertures separately AND there was no need to introduce a new `cold_fit_coron.txt` file. I simply appended the new results from optical models to the existing `cold_fit.txt` file, which has also been slightly modified to account for some typos that were found in doing this work.

The main change in the code is to ensure that the appropriate transformation is selected out of the extended `cold_fit.txt` file. With the introduction of the 4 coron apertures, the old mapping based on the unique NIRCam detector identifier is no longer valid (we have more than one A2- or A5-related master apertures). At the same time also the mapping of transformations  from the `cold_fit.txt` file is no longer unique (e.g. there is more than one OTESKY->NIRCAMASW map).
The unique identifiers are now the complete aperture names of the master apertures, as they appear in the `pysiaf/source_data/siaf_detector_layout.txt` file as input AND the model name in the `cold_fit.txt` file (the 1st column) as output of the mapping.
My code changes mostly deal with this new mapping by:

1. introducing a new version of the mapping dictionary
2. slightly modifying the existing logic for selecting the correct set of transforms.

In the coming commit I am going to commit both the new products of generate_reference_files AND the old files, which should make a comparison easier for the reviewers. I will remove the old files in a following "clean up" commit before asking to merge this PR.
I have verified that:

- the 10 pre-existing distortion files for the imaging master apertures are identical to the newly generated ones 
- the new `nircam_siaf_alignment.txt ` file is identical  to the old one for what concerns the 10 imaging apertures and VERY similar for the 4 coron ones. Changes between the old and new V2/V3 positions for the coron apertures are expected as they are at the very core of this whole effort. The changes seem reasonable, but I'd appreciate feedback on how to veriufy that this is indeed the case
- there are no macroscopic problems in the new 4 distortion files I am going to deliver. In particular I have verified that the plate scale is sensible. Again this just tell me I have not mixed up transform directions and/or made big errors, but does not completely validate the whole work

As I said, I am happy to get feedback and suggestions on what test we can conduct to make sure the new distortion files work as expected. Perhaps a simple plot of the FoV using these apertures? And maybe combined with plots of master and child apertures for coronography?

**Comment by mgennaro** [comment]
I just removed the "old" files completely, they will be still accessible in github if the need arises, but hopefully that will never have to happen...again

**Comment by shanosborne** [comment]
This data has been approved via a comment in https://jira.stsci.edu/browse/JWSTSIAF-174 and is now ready to be merged whenever we start building the CR

**Pull request merged**
