### PR TITLE
Update MIRI TA apertures

### PR DESCRIPTION
**Pull request by Johannes-Sahlmann**

### CODE REVIEW

**Comment by Johannes-Sahlmann** [comment]
Is it possible that @brynickson is not part of the spacetelescope organization? I cannot find that username in https://github.com/orgs/spacetelescope/people?utf8=%E2%9C%93&query=brynickson
and I think that is what I cannot set them as reviewer.

**Comment by drlaw1558** [comment]
Hm, looks like Bryony is not part of the spacetelescope organization and Dean doesn't have a github account that I can find.

**Comment by drlaw1558** [comment]
I'll work on getting one or both of them set up so that they can be included.

**Comment by drlaw1558** [comment]
Bryony is now in the spacetelescope github organization and should be able to be tagged

**Comment by Johannes-Sahlmann** [comment]
SOCPRD CR deadline is April 5. Please approve by April 3rd.

**Comment by brynickson** [comment]
Looks good to me.

**Pull request merged**
