### PR TITLE
added filter-dependent apertures for NIS_AMI1

### PR DESCRIPTION
**Pull request by goudfroo**
Please review changes to niriss_siaf_aperture_definition.txt. I ran generate_niriss.py without errors with this file as input.

### CODE REVIEW

**Comment by mfixstsci** [comment]
Hey @goudfroo -- thank you for submitting these updates. Just to make sure, these are the apertures you are adding:

- NIS_AMI1_F277W,
- NIS_AMI1_F277W_NRM,
- NIS_AMI1_F380M,
- NIS_AMI1_F380M_NRM,
- NIS_AMI1_F430M,
- NIS_AMI1_F430M_NRM,
- NIS_AMI1_F480M,
- NIS_AMI1_F480M_NRM

**Comment by mfixstsci** [comment]
@goudfroo the testing failures you see are the result of the same issue we were discussing yesterday.

**Comment by goudfroo** [comment]
Correct, Mees.

Regards,
Paul

----
Paul Goudfrooij (he/him)
Observatory Scientist
JWST/NIRISS Deputy Branch Manager and Operations Lead
Space Telescope Science Institute
3700 San Martin Drive
Baltimore, MD 21218, USA
My Website<http://bit.ly/sBvZVe>

-------------------------------------------------
Safe Zone Member
web.jhu.edu/SafeZone<http://web.jhu.edu/SafeZone>

On Apr 5, 2023, at 9:30 AM, Mees Fix ***@***.******@***.***>> wrote:



Hey @goudfroo<https://urldefense.com/v3/__https://github.com/goudfroo__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!yFKwy3opqtsk7vXvsLvlW3L_IC2LQMs73ZW4b8_1ZLrfUXs2ACcpLYlpUsB2hpDmo56Epxc4ujzOJFTHfhrvpAx2fg$> -- thank you for submitting these updates. Just to make sure, these are the apertures you are adding:

  *   NIS_AMI1_F277W,
  *   NIS_AMI1_F277W_NRM,
  *   NIS_AMI1_F380M,
  *   NIS_AMI1_F380M_NRM,
  *   NIS_AMI1_F430M,
  *   NIS_AMI1_F430M_NRM,
  *   NIS_AMI1_F480M,
  *   NIS_AMI1_F480M_NRM

**Comment by goudfroo** [comment]
@mfixstsci and @Witchblade101 - as you probably figured out, I was on vacation until today - but I think you already have the answer to your question: the Jira ticket is https://jira.stsci.edu/browse/JWSTSIAF-262.

**Comment by mfixstsci** [comment]
@Witchblade101 anything you can see holding this up. I see the CI is failing, but thats not unusual these days.

**Review by mfixstsci — APPROVED** [review]
Looks fine to me.

**Comment by Witchblade101** [comment]
All upgraded checks pass.

**Pull request merged**
