### PR TITLE
Repo Clean Up (Additions)

### PR DESCRIPTION
**Pull request by mfixstsci**
* Adding pyproject.toml
* Adding MANIFEST.in

Addresses #313, #307

### CODE REVIEW

**Comment by mfixstsci** [comment]
@pllim same here. Something weird happened with the commit history 😓 do you know what could have happened?

**Comment by pllim** [comment]
See https://github.com/spacetelescope/pysiaf/pull/317#issuecomment-1686886554

**Comment by mfixstsci** [comment]
Okay @pllim I performed the rebase and "think" the history looks better now.

**Comment by pllim** [comment]
You should enable RTD build for PRs to be sure. See https://docs.readthedocs.io/en/stable/pull-requests.html

**Comment by mfixstsci** [comment]
Okay @pllim I performed the rebase and "think" the history looks better now.

> You should enable RTD build for PRs to be sure. See https://docs.readthedocs.io/en/stable/pull-requests.html

@pllim from what I see, there are successful builds under the webhook tab https://github.com/spacetelescope/pysiaf/settings/hooks/52696936?tab=deliveries I am going to add the check as well.

**Comment by pllim** [comment]
> there are successful builds under the webhook tab

I cannot access that page. But if you think RTD would build for a PR now, either try to close/reopen and existing PR, or open a new PR to see if it pops up.

**Comment by pllim** [comment]
I am going to unwatch this PR. But feel free to ping me again if you have specific questions. Thanks and good luck!

**Pull request merged**
