### PR TITLE
fix `pip install` in CI

### PR DESCRIPTION
**Pull request by zacharyburnett**
use `pip install .[test]` @mfixstsci

### CODE REVIEW

**Comment by mfixstsci** [comment]
@zacharyburnett would it be possible, or make sense, to remove the line @pllim and I are talking about in #279? It would be nice to see if the tests are still passing once that is removed. Thanks!

**Comment by pllim** [comment]
LGTM. Yes, Python 3.7 has reached EOL and should be removed, which you did.

**Comment by pllim** [comment]
And yes, would be nice to remove oldest-supported-numpy though it is technically out of scope here. Depends on how many PRs you feel like opening today. Has to be done, but can be here or a follow-up.

**Comment by zacharyburnett** [comment]
sure, I'll remove `oldest-supported-numpy` (not sure why I added it in the first place, sorry), and see

**Comment by mfixstsci** [comment]
Boom, still passing. Thank you @zacharyburnett

**Review by mfixstsci — APPROVED** [review]
LGTM! Need to update docs to make sure we are using python >=3.9

**Comment by pllim** [comment]
A grep like this in root dir should smoke most of them out.

```
grep -ri python . | grep "3\.7"
```

**Comment by zacharyburnett** [comment]
Numpy also dropped supporting Python 3.8 in new versions; should the required Python version in `pyproject.toml` also be updated? 
https://github.com/spacetelescope/pysiaf/blob/f49b529e6544f2f5661f20636481029d69db9aa5/pyproject.toml#L4

There is also a reference in `README.md`: 
https://github.com/spacetelescope/pysiaf/blob/f49b529e6544f2f5661f20636481029d69db9aa5/README.md?plain=1#L136

**Pull request merged**
