### PR TITLE
Repo Clean Up (Removals)

### PR DESCRIPTION
**Pull request by mfixstsci**
* Removing DS_Store
* numpy docs and coverage badge
* Adding .DS_Store to gitignore file as well

addresses #310, #315, #311, #306

### CODE REVIEW

**Comment by mfixstsci** [comment]
@pllim this addresses a couple of issues and the CI is passing. Would you be able to do a quick review? @Witchblade101 is out of town on vacation and I don't want this to go stale.

**Comment by pllim** [comment]
Err... did you try a rebase?

```
git fetch upstream master
git rebase upstream/master
```

**Comment by mfixstsci** [comment]
> Err... did you try a rebase?
> 
> ```
> git fetch upstream master
> git rebase upstream/master
> ```

Hey @pllim I have not with this branch. I believe I did try to rebase the other one which may have caused the issue with the history. This one looks fine, right?

**Comment by pllim** [comment]
Move this to "docs" requirement

https://github.com/spacetelescope/pysiaf/blob/f49b529e6544f2f5661f20636481029d69db9aa5/pyproject.toml#L21

**Comment by pllim** [comment]
> This one looks fine, right?

I cannot tell. It has merge commits.

**Comment by mfixstsci** [comment]
> > This one looks fine, right?
> 
> I cannot tell. It has merge commits.

I see the merge commits from `master` which are incorporating the CI changes @zacharyburnett made to get the tests passing. Besides that the history looks chronological.

**Comment by mfixstsci** [comment]
@Witchblade101 this one is ready for review.

**Review by pllim — APPROVED** [review]

**Review by Witchblade101 — APPROVED** [review]
Looks good

**Pull request merged**
