### PR TITLE
JWSTSIAF-156, add DHS-related apertures to NIRCam SIAF in support of Cycle 4 CfP

### PR DESCRIPTION
**Pull request by mgennaro**

### CODE REVIEW

**Comment by Witchblade101** [comment]
@mgennaro Can you check these conflicts?

**Comment by mgennaro** [comment]
Hi @Witchblade101 , somehow I cannot see the conflicts directly (or please tell me how), but I believe I know what you are seeing, because I merged this PR branch AND PR branch for PR #339 locally and I had to solve some myself. I basically created the 2 PRs in questions both starting from siaf-updates. I then modified the `nircam_apertures_definition` file in each of them separately. Since the 2 modifications are independent (ie they introduce 2 new apertures set, that are different in each PR), that file doesn't show any conflict...good, because that's the only file that truly matters. I changed `generate_nircam` independently in each PR, because for the 2 branches I want to see 2 different sets of plots. Hence, you should generate the plots to attach to the individual SIAF tickets using the branch-specific version of `generate_nircam` OR merge the 2 lists of lists around line 390 into a single list and solve that conflict. merge the PR and work on the merged `siaf-updates` branch (and attach ALL plots to both tickets). All that changes is a list of plotted apertures, i.e. the the code that generates the SIAF itself is unchanged. And I guess the `SIAF.xml` and `SIAF.xlsx` conflicts are coming because you are comparing this PR to the "now" state of `siaf-updates`, which has PR#339 already merged. I think you can ignore merging `SIAF.xml` and `SIAF.xlsx` from this branch into the siaf_updates branch, i.e. you could solve the conflict by deleting either version of those 2 files (either the `siaf-updates` ones or the #341 ones). Then once you merge this branch (and obtain the new `nircam_aperture_definition` and the new `generate_nircam` ) you need to rerun the `generate_nircam` script locally, and add  and commit those SIAF xml/xlsx files to the `siaf-updates` remote branch. You should be able to see the "DHS" apertures in SIAF as well as the "FP6" ones. If you see both sets, then we're good.

**Comment by mfixstsci** [comment]
Looks like its coming from https://github.com/spacetelescope/pysiaf/pull/339 the file changes show the addition of `Relic` which I don't believe the institute is supporting (there are references to python 3.7 there 😓).

**Comment by mfixstsci** [comment]
@Witchblade101 and @mgennaro looks like the tests are passing and the conflicts are resolved. Before merging can we confirm that the apertures are correct?

Thanks!

https://github.com/spacetelescope/pysiaf/blob/c1a01acf92f8eece4692365bb0bd8158be4ee455/generate/generate_nircam.py#L392

**Comment by mgennaro** [comment]
@mfixstsci I confirm that the joined set of aperture names is the correct one

**Review by Witchblade101 — APPROVED** [review]
This looks good

**Pull request merged**
