### PR TITLE
Siaf updates nirspec16may22

### PR DESCRIPTION
**Pull request by charlesrp**
Note: generate_nirspec.py results in two assert errors that are benign - improper field points tested for NRS. The current test routines inappropriately test locations outside the valid range.  Fixed test code gives good results.

### CODE REVIEW

**Review by Witchblade101 — APPROVED** [review]
Approved after review by NRS

**Comment by Witchblade101** [comment]
I missed that this PR was against "master". We need to change it to "siaf-updates" before merging and starting the CR process.

**Comment by mfixstsci** [comment]
@Witchblade101 just changed the base to `siaf-updates`. If you want to re-review because it can cause history gaps.

**Comment by Witchblade101** [comment]
History looks good so I'll go ahead and merge.

**Pull request merged**
