### PR TITLE
Address issues raised in #15

### PR DESCRIPTION
**Pull request by Johannes-Sahlmann**
Fix corner calculation for NIRSpec.
Fix tranformation to/from det frame for NIRSpec.

### CODE REVIEW

**Comment by Johannes-Sahlmann** [comment]
Thanks. I will include code to prevent these transformations to be used for NRS_FULL_MSA and NRS_VIGNETTED_MSA.

Does it work properly for NRS1_FP1MIMF?

**Comment by charlesrp** [comment]
Hello Johannes:

Actually NRS1_FP1MIMF doesn’t work if one tries to go to a detector frame.
The corners and reference point functions do seem to work if one sticks to IDL and/or tel frames.

Why is this one different than the other SLIT rows line S1600A1?

My earlier tests had included 
 - NRS_S1600_A1_SLIT
- NRS_S200B1_SLIT  (goes properly to NRS2)
- NRS_FIELD1_MSA4
- NRS1_FULL

But I hadn't specifically tested any of the MIMF apertures until now.

**Comment by charlesrp** [comment]
My previous checks consisted of verifying that the correct reference points and corners were being pulled and checking that going directly from aperture to detector coordinates gave the same results whether using the detector or the slit aperture name. I've now written and tested test code that works with pytest to do those checks for all the slits with a parent aperture.   

However, in writing the tests I realized I was only doing the test in one direction - from idl or tel to det or sci.  It turns out that the reverse transforms starting from the detector and trying to go to the aperture coordinate idl or tel values don't work at all. 

This will be a less common use case, as if coordinates are measured on the detector frame one would normally use the detector aperture name to convert to V2,V3.  However, one might want to ask where given det or sic coordinates are in a slit's idl frame to figure out to where in the slit the detector pixel maps.  I.e., for a NIRSpec slit aperture, one can now do without any problem
In [22]: xic, yic = aperture.idl_to_det(ixc, iyc)
but attempting the following results in an error 
In [23]: ixc2, iyc2 = aperture.det_to_idl(xic, yic)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-23-fad192ec8404> in <module>()
----> 1 ixc2, iyc2 = aperture.det_to_idl(xic, yic)

~/Documents/jwst/siaf/tools/pysiaf/pysiaf/aperture.py in det_to_idl(self, *args)
    892 
    893     def det_to_idl(self, *args):
--> 894         return self.sci_to_idl(*self.det_to_sci(*args))
    895 
    896     def det_to_tel(self, *args):

~/Documents/jwst/siaf/tools/pysiaf/pysiaf/aperture.py in det_to_sci(self, XDet, YDet, *args)
   1673         """Use parent aperture if SLIT."""
   1674         if self.AperType == 'SLIT':
-> 1675             return self._parent_aperture.det_to_sci(self, XDet, YDet, *args)
   1676         else:
   1677             return super(NirspecAperture, self).det_to_sci(XDet, YDet, *args)

~/Documents/jwst/siaf/tools/pysiaf/pysiaf/aperture.py in det_to_sci(self, XDet, YDet, *args)
   1675             return self._parent_aperture.det_to_sci(self, XDet, YDet, *args)
   1676         else:
-> 1677             return super(NirspecAperture, self).det_to_sci(XDet, YDet, *args)
   1678 
   1679 

~/Documents/jwst/siaf/tools/pysiaf/pysiaf/aperture.py in det_to_sci(self, XDet, YDet, *args)
    811     def det_to_sci(self, XDet, YDet, *args):
    812         """ Detector to Science, following Section 4.1 of JWST-STScI-001550"""
--> 813         X_model, Y_model = self.detector_transform('det', 'sci', *args)
    814         return X_model(XDet - self.XDetRef, YDet - self.YDetRef), Y_model(XDet - self.XDetRef,
    815                                                                           YDet - self.YDetRef)

~/Documents/jwst/siaf/tools/pysiaf/pysiaf/aperture.py in detector_transform(self, from_system, to_system, angle_deg, parity)
    641             angle_deg = getattr(self, 'DetSciYAngle')
    642 
--> 643         x_model_1, y_model_1 = linear_transform_model(from_system, to_system, parity, angle_deg)
    644 
    645         if from_system == 'det':

~/Documents/jwst/siaf/tools/pysiaf/pysiaf/aperture.py in linear_transform_model(from_system, to_system, parity, angle_deg)
   1447     """
   1448     if type(angle_deg) != float:
-> 1449         raise TypeError('Angle has to be a float. It is {}'.format(angle_deg))
   1450     # print(angle_deg)
   1451 

TypeError: Angle has to be a float. It is [ 999.22851702  983.98864388  983.98101361  999.22162918]

**Comment by Johannes-Sahlmann** [comment]
I incorporated @charlesrp SLIT test and the 'reverse' transforms.

**Pull request merged**
