### PR TITLE
JSOCOPS-18, NRC-21, NRC-21b updates to SIAF

### PR DESCRIPTION
**Pull request by mgennaro**
Work in progress, creating the PR to start dumping the updates as they become available

### CODE REVIEW

**Comment by Witchblade101** [comment]
Thanks, Mario.

**Comment by mgennaro** [comment]
I realized I had opened the PR against master. Went back to using siaf-updates as the base

**Comment by Witchblade101** [comment]
As a quick check I generated the products and looked at the values in nircam_diff_PRDOPSSOC-045_pre-delivery.txt. It look slike the expected changes (so far) are there.

**Comment by mgennaro** [comment]
There will be seevral warning messages when running the generate scripts.

**Comment by mfixstsci** [comment]
@mgennaro Thank you for the update. Are these warnings about the apertures the same mentioned in your PR #219?

**Comment by mgennaro** [comment]
The PR is ready for review. NIRCam 21 and 21-b job is done! @mfixstsci @Witchblade101

**Comment by Witchblade101** [comment]
Generating files now

**Comment by Witchblade101** [comment]
Output of generate_nircam.py below. I believe these are all expected warnings. No errors.

(pysiaf-37) minmei:generate dlong$ python generate_nircam.py
generate_nircam.py:111: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  polynomial_degree = np.int((np.sqrt(8 * number_of_coefficients + 1) - 3) / 2)
generate_nircam.py:166: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  v2_offset = np.float(wedge_offsets['v2_offset'][wedge_offsets['name'] == sca_name])
generate_nircam.py:167: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  v3_offset = np.float(wedge_offsets['v3_offset'][wedge_offsets['name'] == sca_name])
Verification WARNING: NRCA1_GRISMTS has non-integer sum between YDetRef 1082.7145285391678 and YSciRef 1082.7145285391678 DetSciYAngle 0
Verification WARNING: NRCA1_GRISMTS256 has non-integer sum between YDetRef 167.95021227331313 and YSciRef 167.95021227331313 DetSciYAngle 0
Verification WARNING: NRCA1_GRISMTS128 has non-integer sum between YDetRef 167.95021227331313 and YSciRef 65.95021227331311 DetSciYAngle 0
Verification WARNING: NRCA1_GRISMTS64 has non-integer sum between YDetRef 167.95021227331313 and YSciRef 33.95021227331312 DetSciYAngle 0
Verification WARNING: NRCA5_TAGRISMTS32_F405N has non-integer sum between YDetRef 110.693 and YSciRef 16.693 DetSciYAngle 0
Verification WARNING: NRCB4_GRISMTS256 has non-integer sum between YDetRef 176.0938385408218 and YSciRef 176.0938385408218 DetSciYAngle 0
Verification WARNING: NRCB4_GRISMTS128 has non-integer sum between YDetRef 176.0938385408218 and YSciRef 65.09383854082179 DetSciYAngle 0
Verification WARNING: NRCB4_GRISMTS64 has non-integer sum between YDetRef 176.0938385408218 and YSciRef 33.09383854082179 DetSciYAngle 0
Verification WARNING: NRCA5_MASK430R has non-integer sum XDetRef 1075.5 and XSciRef 160.7 DetSciYAngle 0
Verification WARNING: NRCA5_FULL_MASK430R has non-integer sum XDetRef 1075.5 and XSciRef 973.7 DetSciYAngle 0
Verification WARNING: NRCA4_MASKSWB_NARROW has non-integer sum between YDetRef 535.5 and YSciRef 335.7 DetSciYAngle 180
Verification WARNING: NRCA4_FULL_MASKSWB_NARROW has non-integer sum between YDetRef 535.5 and YSciRef 1508.7 DetSciYAngle 180
Verification WARNING: NRCA5_MASKLWB has non-integer sum between YDetRef 1682.3 and YSciRef 175.3 DetSciYAngle 0
Verification WARNING: NRCA5_FULL_MASKLWB has non-integer sum between YDetRef 1682.3 and YSciRef 1682.3 DetSciYAngle 0
Verification WARNING: NRCA5_MASKLWB_F300M has non-integer sum between YDetRef 1682.1 and YSciRef 175.1 DetSciYAngle 0
Verification WARNING: NRCA5_FULL_MASKLWB_F300M has non-integer sum between YDetRef 1682.1 and YSciRef 1682.1 DetSciYAngle 0
Verification WARNING: NRCA5_MASKLWB_F277W has non-integer sum between YDetRef 1682.1 and YSciRef 175.1 DetSciYAngle 0
Verification WARNING: NRCA5_FULL_MASKLWB_F277W has non-integer sum between YDetRef 1682.1 and YSciRef 1682.1 DetSciYAngle 0
Verification WARNING: NRCA5_MASKLWB_F335M has non-integer sum between YDetRef 1682.2 and YSciRef 175.2 DetSciYAngle 0
Verification WARNING: NRCA5_FULL_MASKLWB_F335M has non-integer sum between YDetRef 1682.2 and YSciRef 1682.2 DetSciYAngle 0
Verification WARNING: NRCA5_MASKLWB_F360M has non-integer sum between YDetRef 1682.2 and YSciRef 175.2 DetSciYAngle 0
Verification WARNING: NRCA5_FULL_MASKLWB_F360M has non-integer sum between YDetRef 1682.2 and YSciRef 1682.2 DetSciYAngle 0
Verification WARNING: NRCA5_MASKLWB_F356W has non-integer sum between YDetRef 1682.2 and YSciRef 175.2 DetSciYAngle 0
Verification WARNING: NRCA5_FULL_MASKLWB_F356W has non-integer sum between YDetRef 1682.2 and YSciRef 1682.2 DetSciYAngle 0
Verification WARNING: NRCA5_MASKLWB_F410M has non-integer sum between YDetRef 1682.2 and YSciRef 175.2 DetSciYAngle 0
Verification WARNING: NRCA5_FULL_MASKLWB_F410M has non-integer sum between YDetRef 1682.2 and YSciRef 1682.2 DetSciYAngle 0
Verification WARNING: NRCA5_MASKLWB_F430M has non-integer sum between YDetRef 1682.3 and YSciRef 175.3 DetSciYAngle 0
Verification WARNING: NRCA5_FULL_MASKLWB_F430M has non-integer sum between YDetRef 1682.3 and YSciRef 1682.3 DetSciYAngle 0
Verification WARNING: NRCA5_MASKLWB_F460M has non-integer sum between YDetRef 1682.4 and YSciRef 175.4 DetSciYAngle 0
Verification WARNING: NRCA5_FULL_MASKLWB_F460M has non-integer sum between YDetRef 1682.4 and YSciRef 1682.4 DetSciYAngle 0
Verification WARNING: NRCA5_MASKLWB_F480M has non-integer sum between YDetRef 1682.4 and YSciRef 175.4 DetSciYAngle 0
Verification WARNING: NRCA5_FULL_MASKLWB_F480M has non-integer sum between YDetRef 1682.4 and YSciRef 1682.4 DetSciYAngle 0
Verification WARNING: NRCA5_MASKLWB_F444W has non-integer sum between YDetRef 1682.4 and YSciRef 175.4 DetSciYAngle 0
Verification WARNING: NRCA5_FULL_MASKLWB_F444W has non-integer sum between YDetRef 1682.4 and YSciRef 1682.4 DetSciYAngle 0
Verification WARNING: NRCA5_MASKLWB_NARROW has non-integer sum between YDetRef 1682.6 and YSciRef 175.6 DetSciYAngle 0
Verification WARNING: NRCA5_FULL_MASKLWB_NARROW has non-integer sum between YDetRef 1682.6 and YSciRef 1682.6 DetSciYAngle 0
Wrote Siaf to xml file /Users/dlong/miniconda3/envs/pysiaf-37/lib/python3.7/site-packages/pysiaf/pre_delivery_data/NIRCam/NIRCam_SIAF.xml
Wrote Siaf to xlsx file /Users/dlong/miniconda3/envs/pysiaf-37/lib/python3.7/site-packages/pysiaf/pre_delivery_data/NIRCam/NIRCam_SIAF.xlsx
JWST nircam Siaf with 320 apertures
nircam
Wrote difference file to /Users/dlong/miniconda3/envs/pysiaf-37/lib/python3.7/site-packages/pysiaf/pre_delivery_data/NIRCam/nircam_diff_PRDOPSSOC-045_pre-delivery.txt
JWST nircam Siaf with 320 apertures
nircam
Apertures with significant roundtrip error differences:
       AperName           siaf0_metric        siaf0_dx_mean     ...   difference_dx_rms       difference_dy_rms
---------------------- ------------------ --------------------- ... ---------------------- -----------------------
        NRCA1_FULL_OSS 2.9784592999284882  0.021212845002229416 ...  -0.007995011734271931   0.0021498269154450154
        NRCA2_FULL_OSS  3.252378727874207   0.02753756346125556 ...  -0.010177114903210223   -0.005361572853537184
        NRCA3_FULL_OSS  2.830210795282076  0.020883954458669224 ... -7.707898860089858e-05    0.004240543664712614
        NRCA4_FULL_OSS  4.181905048945371  0.027127897083079233 ...   0.009369712245761315    0.004418079572705038
        NRCA5_FULL_OSS 3.3357754694389534  0.010408350622461739 ...   0.010491853042610572    0.010133301955276687
        NRCB1_FULL_OSS  3.311552138926007   0.02803234435825857 ...   0.004641786197625539    0.007098252470140244
        NRCB2_FULL_OSS  3.002041181346463   0.02068395878687397 ...   0.015470233018341623    0.038013555117926916
        NRCB3_FULL_OSS  4.605092917791086  0.027578756085706573 ...    0.05975102407568777     0.03278288196435819
        NRCB4_FULL_OSS  2.816233303002365   0.02157465118185996 ...    0.06113752198454859    0.056884745848509166
        NRCB5_FULL_OSS 3.4188082592840856  0.010371043249936065 ...  0.0019285213498541906  -0.0011592858095187146
            NRCA1_FULL 2.9766540155434225  0.021201579986274054 ...  -0.007997682901429907    0.002155809227654305
            NRCA2_FULL 3.2542834427250757  0.027547826396746588 ...  -0.010173433078422292   -0.005372114339099938
            NRCA3_FULL 2.8316748313622013   0.02089535679565529 ... -5.453610076410105e-05     0.00424708227191504
            NRCA4_FULL 4.1850435513458235  0.027138601073748988 ...   0.009374696010970306    0.004412589354095593
            NRCA5_FULL  3.333639085933961   0.01040547333692075 ...   0.010518818511741385     0.01014335947719353
            NRCB1_FULL   3.31331685540954  0.028041732564233826 ...   0.004644505934789728    0.007099801948007498
            NRCB2_FULL 3.0037371423859867  0.020694606579349965 ...    0.01551097206049963    0.038003819637893586
            NRCB3_FULL  4.608107050699993   0.02758706298618108 ...    0.05975650914471502     0.03279040030040038
            NRCB4_FULL  2.814534216663612  0.021561594548709307 ...   0.061025722729944505     0.05686924426924462
            NRCB5_FULL 3.4186855382364203  0.010369986925866215 ...  0.0019295087122185887  -0.0011645012279042546
                   ...                ...                   ... ...                    ...                     ...
 NRCA4_FULL_TAMASKSWBS  3.287896322893408  0.025192626027354947 ...    0.05662969005874584     0.14708355979435972
     NRCA4_FSTAMASKSWB 10.666522458408384   0.01773717564340011 ...   0.004875872504874708    0.003481199664439818
NRCA4_FULL_FSTAMASKSWB 3.2878963229066773  0.025192626027108245 ...    0.05662968970751954     0.14708355995015282
       NRCA5_TAMASKLWB  4.792738978590481 0.0020573127266146686 ...   0.002932312805880067  0.00017269354510776114
  NRCA5_FULL_TAMASKLWB 2.7846753613211668  0.005079729059963256 ...   0.048519983643120046    0.016934240560303952
      NRCA5_TAMASKLWBL 30.199754951540932  0.008871782212668258 ...  0.0012881722370007456    0.001358221759111226
 NRCA5_FULL_TAMASKLWBL 2.7846753614125346  0.005079729060133787 ...   0.048519983643607455     0.01693424055568001
     NRCA5_FSTAMASKLWB  3.109582193495355 0.0014222548812112378 ...  0.0021639771698959307   0.0006203721363649066
NRCA5_FULL_FSTAMASKLWB 2.7846753613823987  0.005079729060141745 ...    0.04851998364337254    0.016934240553338552
        NRCB1_MASK210R  24.06070883193742  0.049081897455497764 ...   0.006452935892933367   0.0010915885419429758
        NRCB5_MASK335R 5.7699823310062825  0.012085119290382949 ...  -0.003779948995398785   -0.003544056668611586
        NRCB5_MASK430R 3.1011893675933484  0.004670919554101687 ...  -0.001970183270487563  -0.0022830535627542522
         NRCB3_MASKSWB 62.448583953970065  0.045043711611424155 ...    0.03266355160319876    0.023294999054952813
         NRCB5_MASKLWB  10.42674119726003  0.015221653618523305 ... -0.0008675421822703236  -0.0022940109482043735
      NRCB1_TAMASK210R 382.18539864217263   0.05393596468012582 ...  0.0026414407455505177  -0.0004081618642885665
      NRCB5_TAMASK335R 63.107670771989156  0.018549461577834166 ... -0.0005121317994566024  -0.0009386367662110192
      NRCB5_TAMASK430R 10.950267011048137   0.00544441414303023 ...  -0.000922568898927714   -0.000773338153829582
       NRCB3_TAMASKSWB 114.76210840318657  0.043598852466602056 ...   0.008913655374649292   0.0043418604074567085
       NRCB5_TAMASKLWB 22.986238605524324  0.009838335188603758 ...  -0.000550701717850963  -0.0005479710059841936
      NRCB5_TAMASKLWBL  135.3296885737937  0.018977723922423913 ... 0.00021411509773619714 -0.00044459645832947557
      NRCB3_TAMASKSWBS 135.83312772048322   0.04436573252174995 ...   0.006823171294854415   0.0032890237142421865
Length = 215 rows
Writing enhanced SIAF aperture definition file including subarrays and V2/V3 of reference point

Running aperture_transforms test for pre_delivery_siaf

Running aperture_vertices test for pre_delivery_siaf

**Comment by mgennaro** [comment]
Yes, all expected

**Review by Witchblade101 — APPROVED** [review]
All tests pass, output as expected

**Pull request merged**
