### PR TITLE
Dummy release

### PR DESCRIPTION
**Pull request by Witchblade101**
Test PR of a release for PRDOPSSOC-051 using the NRS workaround described in #255 . 

This replaces a mistake in the earlier PR.

### CODE REVIEW

**Comment by Witchblade101** [comment]
Comments from PR #254 that should have been here:

Now this is weird...

Every test passes on my Mac, but test_aperture.py::test_idl_to_tel fails here for NIRISS. I noticed the values are very small- 7e-14. We still get the warnings about 'np.float' being deprecated and that we should switch to 'np.float64' to avoid platform differences. Is that what's going on here?

On my Mac:
`========================================================= test session starts ==========================================================
platform darwin -- Python 3.9.12, pytest-7.1.1, pluggy-1.0.0
rootdir: /Users/dlong/pysiaf, configfile: setup.cfg
collected 32 items

test_aperture.py ...... [ 18%]`

And then on witserv2:
`========================================================= test session starts ==========================================================
platform linux -- Python 3.9.13, pytest-7.1.2, pluggy-1.0.0 -- /user/dlong/linux/miniconda3/envs/pysiaf/bin/python
cachedir: .pytest_cache
rootdir: /home/dlong/pysiaf, configfile: setup.cfg
collected 32 items

test_aperture.py::test_idl_to_tel FAILED [ 3%]`

@tonysohn is it safe to ignore these tests failures here, or is something more serious broken?
@[tonysohn](https://github.com/tonysohn)
Member
tonysohn commented [3 hours ago](https://github.com/spacetelescope/pysiaf/pull/254#issuecomment-1149867221)

@Witchblade101 Was that the exact error message? It's hard to tell whether it's safe to ignore or not just from that...
@[Witchblade101](https://github.com/Witchblade101)
Member
Witchblade101 commented [now](https://github.com/spacetelescope/pysiaf/pull/254#issuecomment-1150120220)

    @Witchblade101 Was that the exact error message? It's hard to tell whether it's safe to ignore or not just from that...

No. To see the full error look at the failed checks for PR https://github.com/spacetelescope/pysiaf/pull/261 (which is what these comments refer to. It was a long night, and Mario's NRC work here is completely innocent!)

**Comment by Witchblade101** [comment]
@tonysohn for completeness here's the full run I just did on my Mac:

`========================================================= test session starts ==========================================================
platform darwin -- Python 3.9.12, pytest-7.1.1, pluggy-1.0.0 -- /Users/dlong/miniconda3/envs/pysiaf/bin/python
cachedir: .pytest_cache
rootdir: /Users/dlong/pysiaf, configfile: setup.cfg
collected 32 items

test_aperture.py::test_idl_to_tel PASSED                                                                                         [  3%]
test_aperture.py::test_hst_fgs_idl_to_tel PASSED                                                                                 [  6%]
test_aperture.py::test_jwst_aperture_transforms PASSED                                                                           [  9%]
test_aperture.py::test_jwst_aperture_vertices PASSED                                                                             [ 12%]
test_aperture.py::test_raw_transformations PASSED                                                                                [ 15%]
test_aperture.py::test_jwst_sky_transformations PASSED                                                                           [ 18%]
test_hst.py::test_hst_aperture_init PASSED                                                                                       [ 21%]
test_hst.py::test_hst_siaf PASSED                                                                                                [ 25%]
test_hst.py::test_hst_amudotrep PASSED                                                                                           [ 28%]
test_iando.py::test_write_jwst_siaf_xml PASSED                                                                                   [ 31%]
test_iando.py::test_write_jwst_siaf_xlsx PASSED                                                                                  [ 34%]
test_match_v2v3.py::test_match_v2v3 PASSED                                                                                       [ 37%]
test_miri.py::test_against_test_data PASSED                                                                                      [ 40%]
test_nirspec.py::test_against_test_data PASSED                                                                                   [ 43%]
test_nirspec.py::test_nirspec_aperture_transforms PASSED                                                                         [ 46%]
test_nirspec.py::test_nirspec_slit_transformations PASSED                                                                        [ 50%]
test_nirspec.py::test_sci_det_consistency PASSED                                                                                 [ 53%]
test_plotting.py::test_aperture_plotting PASSED                                                                                  [ 56%]
test_polynomial.py::test_poly PASSED                                                                                             [ 59%]
test_polynomial.py::test_RotateCoeffs PASSED                                                                                     [ 62%]
test_polynomial.py::test_two_step PASSED                                                                                         [ 65%]
test_polynomial.py::test_invert PASSED                                                                                           [ 68%]
test_polynomial.py::test_ShiftCoeffs PASSED                                                                                      [ 71%]
test_projection.py::test_tangent_plane_projection_roundtrip PASSED                                                               [ 75%]
test_projection.py::test_project_to_tangent_plane PASSED                                                                         [ 78%]
test_projection.py::test_deproject_from_tangent_plane PASSED                                                                     [ 81%]
test_rotations.py::test_attitude PASSED                                                                                          [ 84%]
test_rotations.py::test_attitude_matrix PASSED                                                                                   [ 87%]
test_rotations.py::test_sky_to_tel PASSED                                                                                        [ 90%]
test_rotations.py::test_axial_rotation PASSED                                                                                    [ 93%]
test_rotations.py::test_unit_vector_from_cartesian PASSED                                                                        [ 96%]
test_tools.py::test_jwst_fgs_to_fgs_matrix PASSED                                                                                [100%]

========================================================= 32 passed in 31.71s ==========================================================`

**Comment by tonysohn** [comment]
Okay, the fact that this error message is machine dependent (as you implied) tells me that this is not an issue. We can look into this further later, but I'd say we close this for now.

**Comment by Witchblade101** [comment]
Sounds good. I'll open a new issue for test_idl_to_tel later.

**Pull request merged**
