### PR TITLE
Aperture updates related to JSOCOPS-24 (limited to Grism Time Series)

### PR DESCRIPTION
**Pull request by mgennaro**
Under this PR NIRCam will deliver the follwoing changes:

- F444W field point (several GRISMTS apertures in SIAF): Shift X by -94 LW px (DMS oriented). 

- NRCA3 and NRCA1 GRISM128 aperture: Shift Y by -8 SW px (DMS orientation)

- NRCA3 and NRCA1 GRISM64 aperture: Shift Y by -10 SW px (DMS orientation) 

- Adjust the NRCA5_TAGRISMTS32_F405N: 
    - Target should move up and right in DMS/Science coordinates
        - Delta X = +0.165 LW px 
        - Delta Y = +0.16 LW px

### CODE REVIEW

**Comment by mgennaro** [comment]
This PR is ready for review

**Comment by Witchblade101** [comment]
Now this is weird...

Every test passes on my Mac, but test_aperture.py::test_idl_to_tel fails here for NIRISS. I noticed the values are very small- 7e-14.  We still get the warnings about 'np.float' being deprecated and that we should switch to 'np.float64' to avoid platform differences. Is that what's going on here?


On my Mac:
`========================================================= test session starts ==========================================================
platform darwin -- Python 3.9.12, pytest-7.1.1, pluggy-1.0.0
rootdir: /Users/dlong/pysiaf, configfile: setup.cfg
collected 32 items

test_aperture.py ......                                                                                                          [ 18%]`

And then on witserv2:
`========================================================= test session starts ==========================================================
platform linux -- Python 3.9.13, pytest-7.1.2, pluggy-1.0.0 -- /user/dlong/linux/miniconda3/envs/pysiaf/bin/python
cachedir: .pytest_cache
rootdir: /home/dlong/pysiaf, configfile: setup.cfg
collected 32 items

test_aperture.py::test_idl_to_tel FAILED                                                                                         [  3%]`


@tonysohn is it safe to ignore these tests failures here, or is something more serious broken?

**Comment by tonysohn** [comment]
@Witchblade101 Was that the exact error message? It's hard to tell whether it's safe to ignore or not just from that...

**Comment by Witchblade101** [comment]
> @Witchblade101 Was that the exact error message? It's hard to tell whether it's safe to ignore or not just from that...

No. To see the full error look at the failed checks for PR #261 (which is what these comments refer to. It was a long night, and Mario's NRC work here is completely innocent!)

**Comment by Witchblade101** [comment]
Deleted comments that were intended for #261 after copying them there.

**Comment by Witchblade101** [comment]
Complicated conflicts:

remote: Enumerating objects: 31, done.
remote: Counting objects: 100% (31/31), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 31 (delta 26), reused 30 (delta 26), pack-reused 0
Unpacking objects: 100% (31/31), 2.87 KiB | 133.00 KiB/s, done.
From https://github.com/mgennaro/pysiaf
 * branch            JWSTSIAF-186 -> FETCH_HEAD
Removing pysiaf/source_data/NIRSpec/nirspec_siaf_detector_parameters.txt
Removing pysiaf/source_data/NIRSpec/nirspec_siaf_ddc_apername_mapping.txt
Removing pysiaf/source_data/NIRSpec/nirspec_siaf_aperture_definition.txt
Removing pysiaf/source_data/NIRSpec/delivery/test_data/apertures_testData/sky_fpa_projectionMSA_Q4.fits
Removing pysiaf/source_data/NIRSpec/delivery/test_data/apertures_testData/sky_fpa_projectionMSA_Q3.fits
Removing pysiaf/source_data/NIRSpec/delivery/test_data/apertures_testData/sky_fpa_projectionMSA_Q2.fits
Removing pysiaf/source_data/NIRSpec/delivery/test_data/apertures_testData/sky_fpa_projectionMSA_Q1.fits
Removing pysiaf/source_data/NIRSpec/delivery/test_data/TA_testDataWithGWATilt/testDataTA_SCA492F140X.fits
Removing pysiaf/source_data/NIRSpec/delivery/test_data/TA_testDataWithGWATilt/testDataTA_SCA492F110W.fits
Removing pysiaf/source_data/NIRSpec/delivery/test_data/TA_testDataWithGWATilt/testDataTA_SCA492CLEAR.fits
Removing pysiaf/source_data/NIRSpec/delivery/test_data/TA_testDataWithGWATilt/testDataTA_SCA491F140X.fits
Removing pysiaf/source_data/NIRSpec/delivery/test_data/TA_testDataWithGWATilt/testDataTA_SCA491F110W.fits
Removing pysiaf/source_data/NIRSpec/delivery/test_data/TA_testDataWithGWATilt/testDataTA_SCA491CLEAR.fits
Removing pysiaf/source_data/NIRSpec/delivery/test_data/TA_testDataNoTilt/testDataTA_SCA492F140X.fits
Removing pysiaf/source_data/NIRSpec/delivery/test_data/TA_testDataNoTilt/testDataTA_SCA492F110W.fits
Removing pysiaf/source_data/NIRSpec/delivery/test_data/TA_testDataNoTilt/testDataTA_SCA492CLEAR.fits
Removing pysiaf/source_data/NIRSpec/delivery/test_data/TA_testDataNoTilt/testDataTA_SCA491F140X.fits
Removing pysiaf/source_data/NIRSpec/delivery/test_data/TA_testDataNoTilt/testDataTA_SCA491F110W.fits
Removing pysiaf/source_data/NIRSpec/delivery/test_data/TA_testDataNoTilt/testDataTA_SCA491CLEAR.fits
Removing pysiaf/source_data/NIRSpec/delivery/positionsSIAFApertures.fits
Removing pysiaf/source_data/NIRSpec/delivery/disperser_MIRROR_TiltY_TA.gtp
Removing pysiaf/source_data/NIRSpec/delivery/disperser_MIRROR_TiltX_TA.gtp
Removing pysiaf/source_data/NIRSpec/delivery/delivery_SCA492toGWA.pcf
Removing pysiaf/source_data/NIRSpec/delivery/delivery_SCA491toGWA.pcf
Removing pysiaf/source_data/NIRSpec/delivery/delivery_F140X_GWA2XanYan.pcf
Removing pysiaf/source_data/NIRSpec/delivery/delivery_F110W_GWA2XanYan.pcf
Removing pysiaf/source_data/NIRSpec/delivery/delivery_CLEAR_GWA2XanYan.pcf
Removing pysiaf/source_data/NIRSpec/delivery/OTE.pcf
Removing pysiaf/source_data/NIRSpec/delivery/Fore_F290LP.pcf
Removing pysiaf/source_data/NIRSpec/delivery/Fore_F170LP.pcf
Removing pysiaf/source_data/NIRSpec/delivery/Fore_F140X.pcf
Removing pysiaf/source_data/NIRSpec/delivery/Fore_F110W.pcf
Removing pysiaf/source_data/NIRSpec/delivery/Fore_F100LP.pcf
Removing pysiaf/source_data/NIRSpec/delivery/Fore_F070LP.pcf
Removing pysiaf/source_data/NIRSpec/delivery/Fore_CLEAR.pcf
Auto-merging pysiaf/source_data/NIRCam/nircam_siaf_aperture_definition.txt
CONFLICT (rename/delete): pysiaf/pre_delivery_data/NIRCam/nircam_roundtrip_PRDOPSSOC-045-003_pre-delivery.txt deleted in fca75c1d51db63aa26ca3d58e558c39cb2c9280c and renamed to pysiaf/pre_delivery_data/NIRCam/nircam_roundtrip_PRDOPSSOC-051_pre-delivery.txt in HEAD. Version HEAD of pysiaf/pre_delivery_data/NIRCam/nircam_roundtrip_PRDOPSSOC-051_pre-delivery.txt left in tree.
CONFLICT (modify/delete): pysiaf/pre_delivery_data/NIRCam/nircam_enhanced_siaf_aperture_definition.txt deleted in fca75c1d51db63aa26ca3d58e558c39cb2c9280c and modified in HEAD. Version HEAD of pysiaf/pre_delivery_data/NIRCam/nircam_enhanced_siaf_aperture_definition.txt left in tree.
CONFLICT (modify/delete): pysiaf/pre_delivery_data/NIRCam/NIRCam_SIAF.xml deleted in fca75c1d51db63aa26ca3d58e558c39cb2c9280c and modified in HEAD. Version HEAD of pysiaf/pre_delivery_data/NIRCam/NIRCam_SIAF.xml left in tree.
CONFLICT (modify/delete): pysiaf/pre_delivery_data/NIRCam/NIRCam_SIAF.xlsx deleted in fca75c1d51db63aa26ca3d58e558c39cb2c9280c and modified in HEAD. Version HEAD of pysiaf/pre_delivery_data/NIRCam/NIRCam_SIAF.xlsx left in tree.
Auto-merging generate/generate_nircam.py
CONFLICT (content): Merge conflict in generate/generate_nircam.py
Automatic merge failed; fix conflicts and then commit the result.

I'll start resolving things by deleting the previous output files.

**Comment by Witchblade101** [comment]
`<<<<<<< JWSTSIAF-186
            # # make figures for JWSTSIAF-186 Jira ticket
            selected_aperture_names = [['NRCA1_GRISMTS256','NRCA1_GRISMTS128','NRCA1_GRISMTS64'],
            						   ['NRCA3_GRISMTS256','NRCA3_GRISMTS128','NRCA3_GRISMTS64'],
                                       ['NRCA5_TAGRISMTS32','NRCA5_TAGRISMTS32_F405N']
                                       ]
=======
            # # make figures for JWSTSIAF-242 Jira ticket
            selected_aperture_names = [['NRCB{}_SUB160'.format(sca) for sca in ['5','1','2','3','4']],
                                       ['NRCB{}_SUB320'.format(sca) for sca in ['5','1','2','3','4']],
                                       ['NRCB{}_SUB640'.format(sca) for sca in ['5','1','2','3','4']],
                                       ['NRCB5_SUB64P','NRCB1_SUB64P','NRCB5_FULL','NRCB1_FULL'],
                                       ['NRCB5_SUB160P','NRCB1_SUB160P','NRCB5_FULL','NRCB1_FULL'],
                                       ['NRCB5_SUB400P','NRCB1_SUB400P','NRCB5_FULL','NRCB1_FULL'],
                                       ['NRCB1_SUB64P','NRCB1_SUB160P','NRCB1_SUB400P','NRCB5_SUB64P','NRCB5_SUB160P','NRCB5_SUB400P']
                                      ]
>>>>>>> siaf-updates`

I think selected_aperture_names needs to have all of the apertures for both tickets, then we'll be good to go.

**Comment by mgennaro** [comment]
yes, you can choose to have them both, or becuase you already produced the figures for 242, you can actually leave just those for 186 and post those to the JWSTSIAF-186 ticket

**Comment by Witchblade101** [comment]
Right, I see what you're saying. It is just the loop that creates the figures. 

I merged them locally, and it worked with no problems, but I think it makes more sense to do the auxiliary files in their separate tickets.

**Comment by mgennaro** [comment]
I actually could solve the conflict myself (I probably have write privileges because this is my PR). I chose to go with -186 only, becuase we already have the plots for 242

**Comment by Witchblade101** [comment]
Sounds good.

**Comment by mgennaro** [comment]
This approach is also more similar to the typical sequential flow we use for when we do one ticket at a time. I.e. we modify the siaf-upadtes version of generate_nircam to put the "new" plots in that statement that was giving conflict. We usually do not have conflicts because the feature branch is the one and only feature branch that is branched off siaf-updates, but in this case we had 2 branches branched off at the same point in time from siaf-updates and the merging of the jwstsiaf-242 PR into siaf-updates has caused this minor conflict that indeed was expected.

**Review by Witchblade101 — APPROVED** [review]
I think this is what we want. After merging I'll check everything in the new siaf-updates, generate the files, and open a new PR.

**Comment by Witchblade101** [comment]
Uh-oh, we just did something bad. This last PR deleted all of the NIRSpec data:

======================================================= short test summary info ========================================================
FAILED test_aperture.py::test_raw_transformations - FileNotFoundError: [Errno 2] No such file or directory: '/Users/dlong/pysiaf/pysi...
FAILED test_nirspec.py::test_against_test_data - FileNotFoundError: [Errno 2] No such file or directory: '/Users/dlong/pysiaf/pysiaf/...
FAILED test_nirspec.py::test_nirspec_aperture_transforms - FileNotFoundError: [Errno 2] No such file or directory: '/Users/dlong/pysi...
FAILED test_nirspec.py::test_nirspec_slit_transformations - FileNotFoundError: [Errno 2] No such file or directory: '/Users/dlong/pys...
FAILED test_nirspec.py::test_sci_det_consistency - FileNotFoundError: [Errno 2] No such file or directory: '/Users/dlong/pysiaf/pysia...
FAILED test_plotting.py::test_aperture_plotting - FileNotFoundError: [Errno 2] No such file or directory: '/Users/dlong/pysiaf/pysiaf...
==================================================== 6 failed, 26 passed in 24.37s =====================================================

**Comment by Witchblade101** [comment]
I think I can just try a new branch and pull those in from master...

**Comment by mgennaro** [comment]
Holy cow...that is my faults:

https://github.com/spacetelescope/pysiaf/pull/254/commits/569b8d1a40b001d27bdfa765cf4e251b95300955

I was just seeing all these "._" files in my branch and I `git rm`-ed them, but it looks like i removed also the actual files. OMG I am so sorry.

**Pull request merged**
