### PR TITLE
Plotting updates

### PR DESCRIPTION
**Pull request by shanosborne**
These plotting updates come from problems found while investigating issues #1 and #71.

A summary of the changes made:
- Made NIRSpec MSA detector channel plotting possible by plotting the channels from the NRS_FULL apertures
- Removed `NotImplementedError` for `siaf.py` `plot_detector_channels() `
- Add ax argument to `aperture.py` and `siaf.py` `plot_detector_channels()`
- Renamed `plot_all_apertures()` `showchannels` argument to `detector_channels` in order to match `plot_main_apertures()`
- Updated labeling arguments to be more logical between the `siaf.py` and `aperture.py` `plot()` methods
- Updated `siaf.py plot()` docstring to have frame examples in lowercase since that's what the argument expects.

### CODE REVIEW

**Comment by shanosborne** [comment]
I also found an issue with `plot_all_apertures()`, where it tries to apply the `**kwargs` from the function definition in 2 places: `aps = Siaf(instr, **kwargs)` and `aps.plot(clear=False, subarrays=subarrays, **kwargs)`. 

I can either change it so there’s only 1 function that gets the `**kwargs`, or I can sort the kwargs based on the expected arguments of the 2 functions which would look something like: 
```
siaf_kwargs_list = inspect.signature(Siaf).parameters.keys()
siaf_kwargs = dict((key, value) for key, value in kwargs.items() if key in siaf_kwargs_list)
```

However, this second method does assume that there is no overlap in the argument names for the 2 functions (which appears true for now, may not be in the future). Which method would you prefer to use to fix this issue? Do you think the `kwargs` will more likely be used for one of the functions and thus we can just remove the `kwargs` call from the other one?

**Comment by Johannes-Sahlmann** [comment]
Thanks for spotting this. I think `**kwargs` should be passed to `aps.plot` only (definitely not to two different methods).

**Comment by Johannes-Sahlmann** [comment]
PR looks good to me, I just would like the tests to pass before approving.

**Comment by shanosborne** [comment]
It looks like this warning doesn't have anything to do with my changes since it's also present in my master branch. But I'll look into what's causing it.

**Pull request merged**
