### PR TITLE
Cycle 2 / OSS 9.0 enhancement: JWSTSIAF-189/JSOCINT-143 (SW+LW simultaneous coronography)

### PR DESCRIPTION
**Pull request by mgennaro**
This PR delivers the new apertures for the simultaneous operations of the SW and LW NIRCam channel in coronography, slated to become available in Cycle 2 / OSS 9.0.

### CODE REVIEW

**Comment by mgennaro** [comment]
At this time we are not asking to merge this work.
The PR may be altered in the coming months, however the APT developers need a baseline version of the SIAF to proceed with some coding, in support of future OSS development. At this stage I will provide a courtesy copy of the SIAF to the developers. I opened the PR for traceability.

**Comment by mgennaro** [comment]
This PR can be merged, in order to allow support of the PPS 15.0 release

**Comment by mfixstsci** [comment]
@mgennaro looks like we have a failing test, I know we are expecting some test failures with these updates, just want to verify before merging.

**Comment by mgennaro** [comment]
I wouldn't know for sure if the failures you are referring to are among the expected ones.

**Comment by mfixstsci** [comment]
Okay, so according to @Witchblade101 on slack, the re-run jobs button disappears after 30 days of commits. I just made a small push and looks like the tests are still failing.

**Comment by Witchblade101** [comment]
Update progress is being tracked by JWSTSIAF-255

**Review by mfixstsci — APPROVED** [review]
Changes look fine to me. There is still a failing test that we got the green light to bypass after commissioning. Just wanted to make a note before approval.

**Comment by mfixstsci** [comment]
@Witchblade101 and @mgennaro I went ahead and approved the changes.

**Pull request merged**
