### PR TITLE
MIRI CDP-7 imager and LRS updates

### PR DESCRIPTION
**Pull request by drlaw1558**
This updates the MIRI imager distortion solution, fixes an inconsistency in MIRIM_MASK1550, and changes the size of some MIRI TA regions.

### CODE REVIEW

**Comment by drlaw1558** [comment]
@ttemim  @skendrew  to approve for imager and LRS

**Comment by drlaw1558** [comment]
Related to
https://jira.stsci.edu/browse/JWSTSIAF-139
https://jira.stsci.edu/browse/JWSTSIAF-84

**Comment by Johannes-Sahlmann** [comment]
Thanks for this PR. 
Do you want me to process the new files and generate an updated MIRI SIAF in advance of the MIRI-internal approval?

**Comment by drlaw1558** [comment]
Formally I think we should wait until Sarah and Tea approve it, but this PR provides an official way for them to do so.

**Comment by Johannes-Sahlmann** [comment]
Closing this without merge because it is included in and superseded by #81

**Pull request closed without merging**
