### PR TITLE
Adding Github Actions

### PR DESCRIPTION
**Pull request by mfixstsci**

### CODE REVIEW

**Comment by mfixstsci** [comment]
Will need to investigate webhooks for GHA to deliver payloads.

**Comment by mfixstsci** [comment]
@mperrin and @Witchblade101 I am tagging you two as reviewers for discussion about these changes. I have gotten in touch with @jneu to discuss how to pass the github secrets for the user name and password to upload pysiaf to pypi when we release new versions of the software. @jneu said that we should be good to go on his end but before pulling the lever myself I wanted to see if anyone else had any thoughts since we can't release or using travis anymore.

**Comment by mfixstsci** [comment]
@shanosborne has agreed to take a look at this. Thank you Shannon! I am hoping this is straight forward 👍

**Review by shanosborne — COMMENTED** [review]
A couple things I noticed off the bat:
- You should be able to test that the CI runs correctly by opening a PR for this branch on your personal fork. I would try that to check that the ci.yml file is working as expected.
- Don't forget to update the testing badge in the readme file

**Comment by shanosborne** [comment]
Also another note. After you merge this PR and re-trigger the CI in the other open PRs, you'll still see that the Travis CI check is still expected before merging. To update this, you'll go into Settings > Branches, and for each branch, edit it, scroll down to "Require status checks to pass before merging", and from the "Status checks that are required", delete the Travis CI rule and add each of the github actions builds (I think based on your setup there will be one build per python version). I believe that you won't be able to add the github actions tests until they've been run at least 1x.

**Comment by mfixstsci** [comment]
@shanosborne when I look under my local fork, I don't see any runs kicking off. Do you think this is because the travis rule is blocking it?

https://github.com/mfixstsci/pysiaf/actions/new

**Comment by shanosborne** [comment]
@mfixstsci Right, nothing is running because you don't have a PR open. Open a PR for this branch on your personal fork and that should kick off the CI

**Comment by mfixstsci** [comment]
> @mfixstsci Right, nothing is running because you don't have a PR open. Open a PR for this branch on your personal fork and that should kick off the CI

https://github.com/mfixstsci/pysiaf/pull/2

Hmmm, like this? Because I don't see the checks or the workflow runs showing up.

**Comment by shanosborne** [comment]
Yes, a PR like that is exactly what I did and it triggered the CI automatically. You can see my attempts at adding GHA on my  fork of webbpsf here https://github.com/shanosborne/webbpsf/pull/3 and on my fork's Actions tab (back to the last page)

For me, it auto-triggered the CI and then gave me an error because I implemented something wrong. My best guess is that it's not triggering because something in the file is wrong. Maybe the `on: push/pull request` part. Try setting it like `on: [push, pull_request]` and see if that helps it recognize that it should start.

**Comment by mfixstsci** [comment]
@shanosborne that makes sense. It looks like it's only triggered on the default branch as of right now!

**Comment by mfixstsci** [comment]
@shanosborne looks like the tests are all passing. I added some flags to not run some tests that write and delete directories etc. I am sure there is something I could do here to fix this but I don't want to hold this PR up.

https://github.com/mfixstsci/pysiaf/actions/runs/1234993349

Assuming the `publish-to-pypi` job looks good, could we merge?

**Review by shanosborne — APPROVED** [review]
Glad to see the tests passing. I'd still update the badge in the README so it doesn't show failing anymore, but that can happen separately. This looks good for a first pass.

**Review by Witchblade101 — APPROVED** [review]

**Comment by mfixstsci** [comment]
@shanosborne @Witchblade101 thank you for reviewing. I merged the request and all of the tests are passing:

https://github.com/spacetelescope/pysiaf/actions

**Pull request merged**
