### PR TITLE
WIP: Miri interface

### PR DESCRIPTION
**Pull request by Johannes-Sahlmann**
Introduces changes to the interface file packaging and format.

### CODE REVIEW

**Comment by drlaw1558** [comment]
I'm not sure I follow why you aren't using miri_siaf_ima.txt in the code; if there are two files containing the aperture information, one being used and one not, which should be updated when we need to update values?  It seems they could easily get out of sync?  My intent on creating miri_siaf_ima.txt was for it to replace miri_siaf_aperture_definition.txt so that we have a single place to update values for a delivery in a file similar to the other MIRI apertures (MRS/LRS) living in the delivery/ folder.

If there are additional columns that would be useful to include in miri_siaf_ima.txt (xsciref,ysciref,parent_apertures,dependency_type) I'd be happy to include them to mirror the miri_siaf_aperture_definition.txt format.  Would that work for you?

**Comment by Johannes-Sahlmann** [comment]
I use miri_siaf_aperture_definition.txt because I built the pysiaf generation logic based on the principle that there is one single file that defines the list of all apertures (and the order in which they are written to files). I totally agree that we do not want to have the same information duplicated in two files.

I would like to keep that scheme for consistency with the other instruments. As a possible solution, I propose that you generate miri_siaf_aperture_definition.txt in the current format modified by appending several columns (v2ll, v2ul, v2ur, ...) to the table. When those are not applicable, the entries should be set to `None`. miri_siaf_aperture_definition.txt would then essentially be a merge of the three files that you produced (astropy.table provides `join` methods that will help with).

miri_siaf_aperture_definition.txt will then move into the delivery/ folder and I will adapt the pysiaf code accordingly. The other three .txt files will no longer be needed.

What do you think?

**Comment by drlaw1558** [comment]
I think that should work; I'll need to adjust a few things on my end to keep the file generation clean/automated, but will aim to send a revised single file asap.

**Comment by Johannes-Sahlmann** [comment]
@drlaw1558 I think this is good to go.
I will take the discussion of how/when to merge this PR to JIRA.

**Pull request merged**
