### PR TITLE
PR for NIRCam changes to SIAF that will have impact on OSS8.2 - Nov 6 deadline

### PR DESCRIPTION
**Pull request by mgennaro**

### CODE REVIEW

**Comment by mgennaro** [comment]
This PR can now be reviewed.
It is supposed to close JWSTSIAF-118, JWSTSIAF-77.

In this PR we changed the subarray locations and corresponding reference positions of all NIRCam module A coronographic apertures, based on CV3 data.

The changes are all in the nircam siaf aperture definition file. We have used the generate_nircam to verify that the apertures appear in the expected location in the V2,V3 plane.
@JAStansberry

**Comment by shanosborne** [comment]
@Johannes-Sahlmann, @mgennaro already ran the `generate_nircam.py` script and committed the files to this PR. I re-ran the script and confirmed that our files are the same. So if these files look good to you I’ll add them and the plots to the JIRA ticket

**Comment by Johannes-Sahlmann** [comment]
I approved this, but please do not merge until we get the JSOCINT/RCB approval and the go-ahead from NIRCam.

**Comment by mgennaro** [comment]
This PR can be reviewed. In addition to changes related to JWSTSIAF-118, JWSTSIAF-77 it now contains the changes related to JWSTSIAF-124, JWSTSIAF-162.

**Comment by shanosborne** [comment]
@Johannes-Sahlmann would like to review these new SIAF files before I post in the JIRA issues?

**Comment by Johannes-Sahlmann** [comment]
Thanks @shanosborne. Please proceed to the Jira.

**Pull request merged**
