### PR TITLE
Modify Coron outer TA regions

### PR DESCRIPTION
**Pull request by drlaw1558**
Change outer coronagraphic TA regions to 48x48 pixels and update corners accordingly to keep same reference points in the middle of region.

### CODE REVIEW

**Comment by drlaw1558** [comment]
@brynickson should check this too

**Comment by drlaw1558** [comment]
Addresses https://jira.stsci.edu/browse/JWSTSIAF-145

**Comment by Johannes-Sahlmann** [comment]
@drlaw1558 can I go ahead and produce the new SIAF.xml based on the updated input?
Probably, I will branch off from this PR and open an independent PR against master (like I did in #81). Is that OK?

**Comment by drlaw1558** [comment]
Sounds good, please do.

**Comment by Johannes-Sahlmann** [comment]
Closing this since it is now part of #86

**Pull request closed without merging**
