### PR TITLE
This is a PR to check RTD documentation builds

### PR DESCRIPTION
**Pull request by sosey**

### CODE REVIEW

**Comment by Witchblade101** [comment]
Looking good so far. Let me know when you're finished and I'll try to get it reviewed.

**Comment by sosey** [comment]
This PR duplicated work also done in #318 @mfixstsci looks like all the checks are finally passing. Up to you which PR to merge, both should have all your contributions :)

**Review by Witchblade101 — APPROVED** [review]
I'm approving this because I like all the pretty green lights. Keeping #318 open to double check if it has anything missed here.

**Comment by mfixstsci** [comment]
Thanks @Witchblade101 and @sosey! I was working on ExoCTK Friday so I was a little touch and go. Glad this is finally in!

**Pull request merged**
