### PR TITLE
Update generate_miri script for MIRI cdp7

### PR DESCRIPTION
**Pull request by Johannes-Sahlmann**
Update generate miri

### CODE REVIEW

**Comment by Johannes-Sahlmann** [comment]
@drlaw1558: note that I made some changes to remove/mask stsci machine and user names in an effort to clean up this repo with security concerns in mind.

**Comment by drlaw1558** [comment]
Fair point- I'll remove that from my generating script.  More on PR81 soon.

**Comment by Johannes-Sahlmann** [comment]
@shanosborne can you please give this a quick review? 
thanks

**Comment by Johannes-Sahlmann** [comment]
@shanosborne that is because the test by default works with the current PRD SIAF. For this one PR, that will fail. In the future I plan to remove that xfail mark from the test.

**Comment by ColinRCox** [comment]
I have now looked at the angle changes. Understood and approved.

**Pull request merged**
