### PR TITLE
Update master with PRDOPSSOC-051 for Release 0.17.0

### PR DESCRIPTION
**Pull request by Witchblade101**
Same data as PR #262

### CODE REVIEW

**Comment by mfixstsci** [comment]
@Witchblade101 something strange is going on here. There are 93 file changes 😱 It looks like someone somewhere along the way added hidden files (files that start with `.` to the repo). This includes `.DS_STORE` files/directories. I am assuming since the files have the same exact names as the files we track, they are the back up files the editors make in case of a crash. We should probably remove those.

**Comment by Witchblade101** [comment]
I _think_ it's OK now?

**Comment by mfixstsci** [comment]
@Witchblade101 close, let me fork it and I'll push back up

**Comment by Witchblade101** [comment]
The vagaries of written English: Do you want me to close this PR so you can submit a new one, or did you mean we are close to being finished?

**Comment by mfixstsci** [comment]
@Witchblade101 no it's okay, I was just able to push directly to you PR after checking it out. So now if you look at the file list, there shouldn't be any new additional files except the files we are adding to the data directory (PRDOPSSOC-051).

**Comment by Witchblade101** [comment]
The new changes to both PRs look good. All checks now pass.

**Review by mfixstsci — APPROVED** [review]
Looks like we caught all of the files that weren't supposed to be add.. Went from 90ish down to 50ish. All of the new PRD data is included too.

**Pull request merged**
